apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/cloneURI: https://github.com/jenkins-x-charts/jx-build-templates.git
  creationTimestamp: "2020-07-20T18:50:22Z"
  generation: 1
  labels:
    branch: PR-1533
    build: "7"
    context: pr-build
    jenkins.io/pipelineType: build
    lighthouse.jenkins-x.io/baseSHA: b5bf878e8a278681117619aa12053431ab743415
    lighthouse.jenkins-x.io/branch: PR-1533
    lighthouse.jenkins-x.io/buildNum: "7"
    lighthouse.jenkins-x.io/context: pr-build
    lighthouse.jenkins-x.io/id: f46327af-b47e-11ea-b797-9256b7b8d9b0
    lighthouse.jenkins-x.io/lastCommitSHA: 3bb45bf8478b267bc38e8ad5ad6356cfb8a97d0f
    lighthouse.jenkins-x.io/refs.org: jenkins-x-charts
    lighthouse.jenkins-x.io/refs.repo: jx-build-templates
    owner: jenkins-x-charts
    repository: jx-build-templates
    tekton.dev/pipeline: jenkins-x-charts-jx-build-templ-wbbx6-7
  name: jenkins-x-charts-jx-build-templ-wbbx6-7
  namespace: jx
  resourceVersion: "16699294"
  selfLink: /apis/tekton.dev/v1/namespaces/jx/pipelineruns/jenkins-x-charts-jx-build-templ-wbbx6-7
  uid: dd626c56-cab9-11ea-a610-42010a8400cb
spec:
  params:
  - name: version
    value: 0.0.0-SNAPSHOT-PR-1533-7
  - name: build_id
    value: "7"
  pipelineRef:
    apiVersion: tekton.dev/v1
    name: jenkins-x-charts-jx-build-templ-wbbx6-7
  taskRunTemplate:
    podTemplate: {}
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
  computeResources:
  - name: jenkins-x-charts-jx-build-templ-wbbx6
    resourceRef:
      apiVersion: tekton.dev/v1
      name: jenkins-x-charts-jx-build-templ-wbbx6
status:
  startTime: "2020-07-20T18:50:22Z"
  completionTime: "2020-07-20T18:50:43Z"
  conditions:
  - lastTransitionTime: "2020-07-20T18:50:43Z"
    message: TaskRun jenkins-x-charts-jx-build-templ-wbbx6-7-from-build-pack-zjcjs
      has failed
    reason: Failed
    status: "False"
    type: Succeeded
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: jenkins-x-charts-jx-build-templ-wbbx6-7-from-build-pack-zjcjs
