kind: LighthouseJob
apiVersion: lighthouse.jenkins.io/v1alpha1
metadata:
  name: f46327af-b47e-11ea-b797-9256b7b8d9b0
  namespace: jx
  resourceVersion: '3'
  creationTimestamp: 
  labels:
    created-by-lighthouse: 'true'
    lighthouse.jenkins-x.io/branch: PR-813
    lighthouse.jenkins-x.io/buildNum: '7828158075477027098'
    lighthouse.jenkins-x.io/context: github
    lighthouse.jenkins-x.io/job: github
    lighthouse.jenkins-x.io/refs.org: jenkins-x
    lighthouse.jenkins-x.io/refs.pull: '813'
    lighthouse.jenkins-x.io/refs.repo: lighthouse
    lighthouse.jenkins-x.io/type: presubmit
  annotations:
    lighthouse.jenkins-x.io/job: github
spec:
  type: presubmit
  agent: tekton-pipeline
  namespace: jx
  job: github
  refs:
    org: jenkins-x
    repo: lighthouse
    repo_link: https://github.com/jenkins-x/lighthouse-client
    base_ref: master
    base_sha: e8d56b5ee9671599c75644af574a251dd3b94a5c
    base_link: https://github.com/jenkins-x/lighthouse-client/commit/e8d56b5ee9671599c75644af574a251dd3b94a5c
    pulls:
    - number: 813
      author: abayer
      sha: dd64c739442d505cf5381e2a14b60968e8a0d86e
      link: https://github.com/jenkins-x/lighthouse-client/pull/813.diff
      commit_link: https://github.com/jenkins-x/lighthouse-client/pull/813/commits/dd64c739442d505cf5381e2a14b60968e8a0d86e
      author_link: https://github.com/abayer
    clone_uri: https://github.com/jenkins-x/lighthouse-client.git
  context: github
  rerun_command: "/test github"
  pipeline_run_spec:
    pipelineRef:
      name: jenkins-x-charts-jx-build-templ-wbbx6-7
      apiVersion: tekton.dev/v1beta1
    timeouts:
      pipeline: 240h0m0s
    taskRunTemplate:
      podTemplate: {}
      serviceAccountName: tekton-bot
status:
  state: pending
