apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/cloneURI: https://github.com/jenkins-x/lighthouse-client.git
  creationTimestamp: "2020-07-20T17:29:24Z"
  generation: 1
  labels:
    branch: PR-854
    build: "4"
    context: bbs
    jenkins.io/pipelineType: build
    lighthouse.jenkins-x.io/baseSHA: 82747f50259ef389d4ec8e7185c327c657faec02
    lighthouse.jenkins-x.io/branch: PR-854
    lighthouse.jenkins-x.io/buildNum: "4"
    lighthouse.jenkins-x.io/context: github
    lighthouse.jenkins-x.io/id: f46327af-b47e-11ea-b797-9256b7b8d9b0
    lighthouse.jenkins-x.io/lastCommitSHA: feb00a651ac860c842d02b9eac3cc2fc9eb06c10
    lighthouse.jenkins-x.io/refs.org: jenkins-x
    lighthouse.jenkins-x.io/refs.repo: lighthouse
    owner: jenkins-x
    repository: lighthouse
    tekton.dev/pipeline: jenkins-x-lighthouse-pr-854-bbs-d5q9c-4
  name: jenkins-x-lighthouse-pr-854-bbs-d5q9c-4
  namespace: jx
  resourceVersion: "16679114"
  selfLink: /apis/tekton.dev/v1/namespaces/jx/pipelineruns/jenkins-x-lighthouse-pr-854-bbs-d5q9c-4
  uid: 8e1712a0-caae-11ea-a610-42010a8400cb
spec:
  params:
  - name: version
    value: 0.0.0-SNAPSHOT-PR-854-4
  - name: build_id
    value: "4"
  pipelineRef:
    apiVersion: tekton.dev/v1
    name: jenkins-x-lighthouse-pr-854-bbs-d5q9c-4
  taskRunTemplate:
    podTemplate: {}
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
  computeResources:
  - name: jenkins-x-lighthouse-pr-854-bbs-d5q9c
    resourceRef:
      apiVersion: tekton.dev/v1
      name: jenkins-x-lighthouse-pr-854-bbs-d5q9c
status:
  startTime: "2020-07-20T17:29:24Z"
  completionTime: "2020-07-20T18:00:05Z"
  conditions:
  - lastTransitionTime: "2020-07-20T18:00:05Z"
    message: 'Tasks Completed: 1, Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: jenkins-x-lighthouse-pr-854-bbs-d5q9c-4-ci-wbnrf
