apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: jenkins-x-jx-pr-7463-boot-vault-9mbgb-17-e2e-tests-ds74m
status:
  startTime: "2020-07-20T19:56:53Z"
  conditions:
  - lastTransitionTime: "2020-07-20T19:58:36Z"
    message: Not all Steps in the Task have finished executing
    reason: Running
    status: Unknown
    type: Succeeded
  steps:
  - container: step-setup-builder-home
    imageID: docker-pullable://gcr.io/jenkinsxio/builder-jx@sha256:74e5c1ea05f84329f5fb150a46c55ae89288b950c8edb1041af1911516a86b0e
    name: setup-builder-home
    terminated:
      containerID: docker://2a6124bda33744d5710c9ab6d2787db4bfc31aaf1e92725b7c8bbc8dfb0e1f73
      exitCode: 0
      finishedAt: "2020-07-20T19:58:45Z"
      reason: Completed
      startedAt: "2020-07-20T19:58:44Z"
  - container: step-boot-vault-e2e-tests
    imageID: docker-pullable://gcr.io/jenkinsxio/builder-go-nodejs@sha256:e46a06e4bb1ef265389fa10d83ecffee6e3e3391c050ed347d32ccae4fcb26e0
    name: boot-vault-e2e-tests
    running:
      startedAt: "2020-07-20T19:58:12Z"
  - container: step-generate-report
    imageID: docker-pullable://gcr.io/jenkinsxio/builder-nodejs10x@sha256:e7ff71273ddd8a1a3db7aae0cbbbf294d136ffb22416814dc1ba966061d66a51
    name: generate-report
    running:
      startedAt: "2020-07-20T19:58:12Z"
  - container: step-clear-kubeconfig
    imageID: docker-pullable://gcr.io/jenkinsxio/builder-go@sha256:6560c7cddfe1712c840ff6f429fedf961c7ad442c3b3e0f48c4f83f1f29156ed
    name: clear-kubeconfig
    running:
      startedAt: "2020-07-20T19:58:36Z"
  - container: step-stashhtmlreport
    imageID: docker-pullable://gcr.io/jenkinsxio/builder-go@sha256:6560c7cddfe1712c840ff6f429fedf961c7ad442c3b3e0f48c4f83f1f29156ed
    name: stashhtmlreport
    running:
      startedAt: "2020-07-20T19:58:36Z"
  - container: step-source-copy-workspace-7hpkx
    imageID: docker-pullable://busybox@sha256:2131f09e4044327fd101ca1fd4043e6f3ad921ae7ee901e9142e6e36b354a907
    name: source-copy-workspace-7hpkx
    terminated:
      containerID: docker://d7b36a57400a1efe415311e6b1516e3e0c7a1ab87454eade9caea6f1f739be85
      exitCode: 0
      finishedAt: "2020-07-20T19:58:44Z"
      reason: Completed
      startedAt: "2020-07-20T19:58:38Z"
  - container: step-create-dir-workspace-tncdr
    imageID: docker-pullable://busybox@sha256:2131f09e4044327fd101ca1fd4043e6f3ad921ae7ee901e9142e6e36b354a907
    name: create-dir-workspace-tncdr
    terminated:
      containerID: docker://e899d802cdbd5e93925451244128ef98c95da5c6f219fd51ba5a9c09e59eb296
      exitCode: 0
      finishedAt: "2020-07-20T19:58:38Z"
      reason: Completed
      startedAt: "2020-07-20T19:58:38Z"
