apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/cloneURI: https://github.com/jenkins-x/jx.git
  creationTimestamp: "2020-07-20T20:15:20Z"
  generation: 1
  labels:
    branch: PR-7463
    build: "18"
    context: unit
    jenkins.io/pipelineType: build
    lighthouse.jenkins-x.io/baseSHA: c47ce72d4e2991a9440e6d954ecbf79d596f9352
    lighthouse.jenkins-x.io/branch: PR-7463
    lighthouse.jenkins-x.io/buildNum: "18"
    lighthouse.jenkins-x.io/context: unit
    lighthouse.jenkins-x.io/id: f46327af-b47e-11ea-b797-9256b7b8d9b0
    lighthouse.jenkins-x.io/lastCommitSHA: 8a3c5f595cdc3162e46390c72a5d22fb9c89d1df
    lighthouse.jenkins-x.io/refs.org: jenkins-x
    lighthouse.jenkins-x.io/refs.repo: jx
    owner: jenkins-x
    repository: jx
    tekton.dev/pipeline: jenkins-x-jx-pr-7463-unit-wbf7v-18
  name: jenkins-x-jx-pr-7463-unit-wbf7v-18
  namespace: jx
  resourceVersion: "16732905"
  selfLink: /apis/tekton.dev/v1/namespaces/jx/pipelineruns/jenkins-x-jx-pr-7463-unit-wbf7v-18
  uid: bc78bda8-cac5-11ea-a610-42010a8400cb
spec:
  params:
  - name: version
    value: 0.0.0-SNAPSHOT-PR-7463-18
  - name: build_id
    value: "18"
  pipelineRef:
    apiVersion: tekton.dev/v1
    name: jenkins-x-jx-pr-7463-unit-wbf7v-18
  taskRunTemplate:
    podTemplate: {}
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
  computeResources:
  - name: jenkins-x-jx-pr-7463-unit-wbf7v
    resourceRef:
      apiVersion: tekton.dev/v1
      name: jenkins-x-jx-pr-7463-unit-wbf7v
status:
  startTime: "2020-07-20T20:15:20Z"
  conditions:
  - lastTransitionTime: "2020-07-20T20:15:20Z"
    message: 'Tasks Completed: 0, Incomplete: 1, Skipped: 0'
    reason: Running
    status: Unknown
    type: Succeeded
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: jenkins-x-jx-pr-7463-unit-wbf7v-18-ci-8r5qw
