name: Upgrade Hermit repos
on:
  schedule:
    # run a bit before midnight when go deps change
    - cron: '0 23 * * *'

  # allow manual triggering
  workflow_dispatch: {}
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://golang:1.15
        env:
          GIT_USER: jenkins-x-bot-test
          GIT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        name: Upgrade hermit
        with:
          entrypoint: ./.github/workflows/upgrade-hermit.sh
